# TRACCC library, part of the ACTS project (R&D line)
#
# (c) 2022-2023 CERN for the benefit of the ACTS project
#
# Mozilla Public License Version 2.0

stages:
  - build
  - test


build_cuda:
  tags: [docker]
  stage: build
  image: ghcr.io/acts-project/ubuntu2004_cuda:v30
  artifacts:
    paths:
      - build
  script:
      - git clone $CLONE_URL src
      - git -C src checkout $HEAD_SHA
      - cmake --preset cuda -DCMAKE_BUILD_TYPE=Release -S src -B build -G Ninja
      - cmake --build build --parallel 2

test_cuda:
  stage: test
  tags: [docker-gpu-nvidia]
  image: ghcr.io/acts-project/ubuntu2004_cuda:v30
  needs:
    - build_cuda
  script:
    - git clone $CLONE_URL src
    - cd src
    - git checkout $HEAD_SHA
    - data/traccc_data_get_files.sh
    - cd ..
    - cd build
    - nvidia-smi
    - ctest --output-on-failure -E "^SeedingValidation/CompareWithActsSeedingTests.*"
